### PR TITLE
Fix buffer sizes in ParseUserName + add some tests

### LINKED ISSUE #24: AccessViolationException in CredUiParseUserName
The more my username is long the more I get this exception:
```
System.AccessViolationException: Tentative de lecture ou d'écriture de mémoire protégée. Cela indique souvent qu'une autre mémoire est endommagée.
  at à AdysTech.CredentialManager.NativeCode.CredUIParseUserName(String userName, StringBuilder user, Int32 userMaxChars, StringBuilder domain, Int32 domainMaxChars)
  at à AdysTech.CredentialManager.CredentialManager.ParseUserName(String usernameBuf, Int32 maxUserName, Int32 maxDomain, String& user, String& domain)
  at à AdysTech.CredentialManager.CredentialManager.PromptForCredentials(String target, CredentialUIInfo credUI, Boolean& save, String& user, String& password, String& domain)
  at à AdysTech.CredentialManager.CredentialManager.PromptForCredentials(String target, Boolean& save, String message, String caption, String& user, String& password, String& domain)
  at à AdysTech.CredentialManager.CredentialManager.PromptForCredentials(String target, Boolean& save, String message, String caption)
```

When quickly looking at the code it seems pass new empty string builders to the native function while max size is 100:

```csharp
StringBuilder user1 = new StringBuilder();
StringBuilder domain1 = new StringBuilder();
user = string.Empty;
domain = string.Empty;
NativeCode.CredentialUIReturnCodes userName = NativeCode.CredUIParseUserName(usernameBuf, user1, maxUserName, domain1, maxDomain);
```

### PR DESCRIPTION
**Pull request by jairbubbles**
Fixes  #24

### CODE REVIEW

File: AdysTech.CredentialManager/Properties/AssemblyInfo.cs [hunk 1]
```diff
@@ -33,4 +33,6 @@
 // by using the '*' as shown below:
 // [assembly: AssemblyVersion("1.0.*")]
 [assembly: AssemblyVersion("1.5.0.0")]
-[assembly: AssemblyFileVersion("1.5.0.0")]
\ No newline at end of file
+[assembly: AssemblyFileVersion("1.5.0.0")]
```
Comment (mvadu) [inline AdysTech.CredentialManager/Properties/AssemblyInfo.cs]: Please increase the minor version No, so that I can push an update to Nuget.

File: CredentialManager.Test/CredentialManagerTest.cs [hunk 2]
```diff
@@ -149,5 +149,39 @@ public void TestGetCredentials_NullUserName()
             Assert.IsTrue(cred1.UserName == cred.UserName && cred1.Password== cred.Password && cred1.Domain == cred.Domain, "Saved and retreived data doesn't match");
         }
 
+        [TestMethod]
```
Comment (mvadu) [inline CredentialManager.Test/CredentialManagerTest.cs]: Please add AppVeyor category i.e. `[TestMethod, TestCategory("AppVeyor")]` so that CI can pick up this test.

File: CredentialManager.Test/CredentialManagerTest.cs [hunk 3]
```diff
@@ -149,5 +149,39 @@ public void TestGetCredentials_NullUserName()
...
+            var longUserName = "ksdqkdbkbqskdbqskdqsdsqdqsdjsqdjqsdjlqsjd@domain.com";
+            string domain;
+            string user;
+            Assert.IsTrue(CredentialManager.ParseUserName(longUserName, 100, 100, out user, out domain));
+
+            Assert.AreEqual(longUserName, user);
+            Assert.AreEqual("", domain);
+        }
+
+        [TestMethod]
```
Comment (mvadu) [inline CredentialManager.Test/CredentialManagerTest.cs]: Please add AppVeyor category i.e. `[TestMethod, TestCategory("AppVeyor")]` so that CI can pick up this test.

File: CredentialManager.Test/CredentialManagerTest.cs [hunk 4]
```diff
@@ -149,5 +149,39 @@ public void TestGetCredentials_NullUserName()
...
+        {
+            var longUserName = "ksdqkdbkbqskdbqskdqsdsqdqsdjsqdjqsdjlqsjd@domain.com";
+            string domain;
+            string user;
+            Assert.IsFalse(CredentialManager.ParseUserName(longUserName, 10, 100, out user, out domain));
+            Assert.AreEqual("", user);
+            Assert.AreEqual("", domain);
+        }
+
+        [TestMethod]
```
Comment (mvadu) [inline CredentialManager.Test/CredentialManagerTest.cs]: Please add AppVeyor category i.e. `[TestMethod, TestCategory("AppVeyor")]` so that CI can pick up this test.

File: CredentialManager.Test/CredentialManagerTest.cs (hunk 2 above)
Comment (jairbubbles) [reply CredentialManager.Test/CredentialManagerTest.cs]: Will do. Maybe you should consider doing the opposite? Run all tests on CI except some tests ?

**Comment by jairbubbles** [comment]
There are two license files:  `License.md` and `LICENSE.md` on the repo, on Windows git doesn't like that as the file system is case insensitive.
